// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlcgen

import (
	"context"
)

const idempotencyKeyExists = `-- name: IdempotencyKeyExists :one
SELECT EXISTS(
    SELECT 1 FROM idempotency_keys WHERE key = $1 AND expires_at > now()
)
`

func (q *Queries) IdempotencyKeyExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, idempotencyKeyExists, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO idempotency_keys (key, expires_at)
VALUES ($1, now() + CAST($2 AS interval))
ON CONFLICT (key) DO NOTHING
`

type InsertIdempotencyKeyParams struct {
	Key         string
	TtlInterval int64
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.ExecContext(ctx, insertIdempotencyKey, arg.Key, arg.TtlInterval)
	return err
}
