// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ProgressPhase string

const (
	ProgressPhaseIdea    ProgressPhase = "idea"
	ProgressPhaseDesign  ProgressPhase = "design"
	ProgressPhaseCoding  ProgressPhase = "coding"
	ProgressPhaseTesting ProgressPhase = "testing"
	ProgressPhaseDemo    ProgressPhase = "demo"
)

func (e *ProgressPhase) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProgressPhase(s)
	case string:
		*e = ProgressPhase(s)
	default:
		return fmt.Errorf("unsupported scan type for ProgressPhase: %T", src)
	}
	return nil
}

type NullProgressPhase struct {
	ProgressPhase ProgressPhase
	Valid         bool // Valid is true if ProgressPhase is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProgressPhase) Scan(value interface{}) error {
	if value == nil {
		ns.ProgressPhase, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProgressPhase.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProgressPhase) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProgressPhase), nil
}

type QuestionStatus string

const (
	QuestionStatusOpen           QuestionStatus = "open"
	QuestionStatusInProgress     QuestionStatus = "in_progress"
	QuestionStatusAwaitingUser   QuestionStatus = "awaiting_user"
	QuestionStatusAssignedMentor QuestionStatus = "assigned_mentor"
	QuestionStatusResolved       QuestionStatus = "resolved"
)

func (e *QuestionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuestionStatus(s)
	case string:
		*e = QuestionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for QuestionStatus: %T", src)
	}
	return nil
}

type NullQuestionStatus struct {
	QuestionStatus QuestionStatus
	Valid          bool // Valid is true if QuestionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuestionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.QuestionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuestionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuestionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuestionStatus), nil
}

type SlackChannelPurpose string

const (
	SlackChannelPurposeProgress SlackChannelPurpose = "progress"
	SlackChannelPurposeQuestion SlackChannelPurpose = "question"
	SlackChannelPurposeNotice   SlackChannelPurpose = "notice"
)

func (e *SlackChannelPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SlackChannelPurpose(s)
	case string:
		*e = SlackChannelPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for SlackChannelPurpose: %T", src)
	}
	return nil
}

type NullSlackChannelPurpose struct {
	SlackChannelPurpose SlackChannelPurpose
	Valid               bool // Valid is true if SlackChannelPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSlackChannelPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.SlackChannelPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SlackChannelPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSlackChannelPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SlackChannelPurpose), nil
}

type UserRole string

const (
	UserRoleParticipant UserRole = "participant"
	UserRoleMentor      UserRole = "mentor"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ChannelPurposeAssignment struct {
	SlackChannelID string
	Purpose        SlackChannelPurpose
	CreatedAt      time.Time
}

type IdempotencyKey struct {
	Key       string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Mentor struct {
	UserID    uuid.UUID
	CreatedAt time.Time
}

type MentorTeamAssignment struct {
	MentorUserID uuid.UUID
	TeamID       uuid.UUID
	CreatedAt    time.Time
}

type Participant struct {
	UserID    uuid.UUID
	TeamID    uuid.UUID
	CreatedAt time.Time
}

type ProgressBody struct {
	ID            uuid.UUID
	ProgressLogID uuid.UUID
	Phase         ProgressPhase
	Sos           bool
	Comment       sql.NullString
	SubmittedAt   time.Time
}

type ProgressLog struct {
	ID            uuid.UUID
	ParticipantID uuid.UUID
	CreatedAt     time.Time
}

type Question struct {
	ID             uuid.UUID
	ParticipantID  uuid.UUID
	Title          string
	SlackChannelID string
	Status         QuestionStatus
	SlackThreadTs  string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type QuestionMentorAssignment struct {
	QuestionID   uuid.UUID
	MentorUserID uuid.UUID
	CreatedAt    time.Time
}

type SlackChannel struct {
	ID        string
	TeamID    uuid.UUID
	CreatedAt time.Time
}

type Staff struct {
	ID          uuid.UUID
	SlackUserID sql.NullString
	Name        string
	Email       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Team struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TeamGithubRepository struct {
	ID            uuid.UUID
	TeamID        uuid.UUID
	GithubRepoUrl string
	EncryptedPat  string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID          uuid.UUID
	SlackUserID string
	Name        string
	Email       string
	Role        UserRole
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
