// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type IdempotencyKey struct {
	Key       string
	CreatedAt time.Time
	ExpiresAt time.Time
}
