// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: progress.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const insertProgressBody = `-- name: InsertProgressBody :exec
INSERT INTO progress_bodies (progress_log_id, phase, sos, comment, submitted_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertProgressBodyParams struct {
	ProgressLogID uuid.UUID
	Phase         ProgressPhase
	Sos           bool
	Comment       sql.NullString
	SubmittedAt   time.Time
}

func (q *Queries) InsertProgressBody(ctx context.Context, arg InsertProgressBodyParams) error {
	_, err := q.db.ExecContext(ctx, insertProgressBody,
		arg.ProgressLogID,
		arg.Phase,
		arg.Sos,
		arg.Comment,
		arg.SubmittedAt,
	)
	return err
}

const insertProgressLog = `-- name: InsertProgressLog :exec
INSERT INTO progress_logs (id, participant_id)
VALUES ($1, $2)
`

type InsertProgressLogParams struct {
	ID            uuid.UUID
	ParticipantID uuid.UUID
}

func (q *Queries) InsertProgressLog(ctx context.Context, arg InsertProgressLogParams) error {
	_, err := q.db.ExecContext(ctx, insertProgressLog, arg.ID, arg.ParticipantID)
	return err
}
