// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questions.sql

package sqlcgen

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findMentorIDsByQuestionID = `-- name: FindMentorIDsByQuestionID :many
SELECT mentor_user_id
FROM question_mentor_assignments
WHERE question_id = $1
`

func (q *Queries) FindMentorIDsByQuestionID(ctx context.Context, questionID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, findMentorIDsByQuestionID, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var mentor_user_id uuid.UUID
		if err := rows.Scan(&mentor_user_id); err != nil {
			return nil, err
		}
		items = append(items, mentor_user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findQuestionByID = `-- name: FindQuestionByID :one
SELECT id, participant_id, title, slack_channel_id, status, slack_thread_ts
FROM questions
WHERE id = $1
`

type FindQuestionByIDRow struct {
	ID             uuid.UUID
	ParticipantID  uuid.UUID
	Title          string
	SlackChannelID string
	Status         QuestionStatus
	SlackThreadTs  string
}

func (q *Queries) FindQuestionByID(ctx context.Context, id uuid.UUID) (FindQuestionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, findQuestionByID, id)
	var i FindQuestionByIDRow
	err := row.Scan(
		&i.ID,
		&i.ParticipantID,
		&i.Title,
		&i.SlackChannelID,
		&i.Status,
		&i.SlackThreadTs,
	)
	return i, err
}

const updateQuestionStatus = `-- name: UpdateQuestionStatus :execresult
UPDATE questions
SET status = $1, updated_at = now()
WHERE id = $2
`

type UpdateQuestionStatusParams struct {
	Status QuestionStatus
	ID     uuid.UUID
}

func (q *Queries) UpdateQuestionStatus(ctx context.Context, arg UpdateQuestionStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateQuestionStatus, arg.Status, arg.ID)
}
