// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	BearerAuthScopes        = "bearerAuth.Scopes"
	InternalTokenAuthScopes = "internalTokenAuth.Scopes"
	StaffBearerAuthScopes   = "staffBearerAuth.Scopes"
)

// CreateIssueRequest defines model for CreateIssueRequest.
type CreateIssueRequest struct {
	Body      string `json:"body"`
	ChannelId string `json:"channel_id"`
	Title     string `json:"title"`
}

// CreateIssueResponse defines model for CreateIssueResponse.
type CreateIssueResponse struct {
	IssueUrl string `json:"issue_url"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// CreateTeamResponse defines model for CreateTeamResponse.
type CreateTeamResponse struct {
	Team TeamResponse `json:"team"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LatestProgressResponse defines model for LatestProgressResponse.
type LatestProgressResponse struct {
	Id             string                 `json:"id"`
	ParticipantId  string                 `json:"participant_id"`
	ProgressBodies []ProgressBodyResponse `json:"progress_bodies"`
}

// ListReposResponse defines model for ListReposResponse.
type ListReposResponse struct {
	Repos []RepoItem `json:"repos"`
}

// ListTeamsResponse defines model for ListTeamsResponse.
type ListTeamsResponse struct {
	Teams []TeamResponse `json:"teams"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string       `json:"token"`
	User  UserResponse `json:"user"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// ProgressBodyResponse defines model for ProgressBodyResponse.
type ProgressBodyResponse struct {
	Comment     string    `json:"comment"`
	Phase       string    `json:"phase"`
	Sos         bool      `json:"sos"`
	SubmittedAt time.Time `json:"submitted_at"`
}

// ProgressListResponse defines model for ProgressListResponse.
type ProgressListResponse struct {
	Data []TeamProgressResponse `json:"data"`
}

// RegisterParticipantRequest defines model for RegisterParticipantRequest.
type RegisterParticipantRequest struct {
	SlackUserId string `json:"slack_user_id"`
	TeamId      string `json:"team_id"`
}

// RegisterParticipantResponse defines model for RegisterParticipantResponse.
type RegisterParticipantResponse struct {
	User UserResponse `json:"user"`
}

// RegisterRepoRequest defines model for RegisterRepoRequest.
type RegisterRepoRequest struct {
	GithubRepoUrl       string `json:"github_repo_url"`
	PersonalAccessToken string `json:"personal_access_token"`
}

// RepoItem defines model for RepoItem.
type RepoItem struct {
	Id       string `json:"id"`
	Owner    string `json:"owner"`
	RepoName string `json:"repo_name"`
}

// SetupPasswordRequest defines model for SetupPasswordRequest.
type SetupPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// StaffLoginRequest defines model for StaffLoginRequest.
type StaffLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// StaffLoginResponse defines model for StaffLoginResponse.
type StaffLoginResponse struct {
	Staff StaffResponse `json:"staff"`
	Token string        `json:"token"`
}

// StaffResponse defines model for StaffResponse.
type StaffResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// TeamProgressResponse defines model for TeamProgressResponse.
type TeamProgressResponse struct {
	LatestProgress *LatestProgressResponse `json:"latest_progress,omitempty"`
	TeamId         string                  `json:"team_id"`
	TeamName       string                  `json:"team_name"`
}

// TeamResponse defines model for TeamResponse.
type TeamResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// UpdateTokenRequest defines model for UpdateTokenRequest.
type UpdateTokenRequest struct {
	PersonalAccessToken string `json:"personal_access_token"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

// ListProgressParams defines parameters for ListProgress.
type ListProgressParams struct {
	TeamId *string `form:"team_id,omitempty" json:"team_id,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SetupPasswordJSONRequestBody defines body for SetupPassword for application/json ContentType.
type SetupPasswordJSONRequestBody = SetupPasswordRequest

// RegisterParticipantJSONRequestBody defines body for RegisterParticipant for application/json ContentType.
type RegisterParticipantJSONRequestBody = RegisterParticipantRequest

// StaffLoginJSONRequestBody defines body for StaffLogin for application/json ContentType.
type StaffLoginJSONRequestBody = StaffLoginRequest

// StaffCreateTeamJSONRequestBody defines body for StaffCreateTeam for application/json ContentType.
type StaffCreateTeamJSONRequestBody = CreateTeamRequest

// RegisterRepositoryJSONRequestBody defines body for RegisterRepository for application/json ContentType.
type RegisterRepositoryJSONRequestBody = RegisterRepoRequest

// UpdateTokenJSONRequestBody defines body for UpdateToken for application/json ContentType.
type UpdateTokenJSONRequestBody = UpdateTokenRequest

// CreateIssueJSONRequestBody defines body for CreateIssue for application/json ContentType.
type CreateIssueJSONRequestBody = CreateIssueRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate user and get JWT token
	// (POST /api/v1/auth/login)
	Login(c *gin.Context)
	// Set password using setup token
	// (POST /api/v1/auth/setup)
	SetupPassword(c *gin.Context)
	// Register a participant in a team (mentor only)
	// (POST /api/v1/participants)
	RegisterParticipant(c *gin.Context)
	// List latest progress by team
	// (GET /api/v1/progress)
	ListProgress(c *gin.Context, params ListProgressParams)
	// Authenticate staff and get JWT token
	// (POST /api/v1/staff/auth/login)
	StaffLogin(c *gin.Context)
	// List all teams (staff only)
	// (GET /api/v1/staff/teams)
	StaffListTeams(c *gin.Context)
	// Create a new team (staff only)
	// (POST /api/v1/staff/teams)
	StaffCreateTeam(c *gin.Context)
	// List GitHub repositories for a team
	// (GET /api/v1/teams/{teamId}/github-repos)
	ListRepositories(c *gin.Context, teamId string)
	// Register a GitHub repository for a team
	// (POST /api/v1/teams/{teamId}/github-repos)
	RegisterRepository(c *gin.Context, teamId string)
	// Remove a GitHub repository
	// (DELETE /api/v1/teams/{teamId}/github-repos/{repoId})
	RemoveRepository(c *gin.Context, teamId string, repoId string)
	// Update GitHub repository token
	// (PUT /api/v1/teams/{teamId}/github-repos/{repoId}/token)
	UpdateToken(c *gin.Context, teamId string, repoId string)
	// Create a GitHub issue (internal)
	// (POST /internal/issues)
	CreateIssue(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// SetupPassword operation middleware
func (siw *ServerInterfaceWrapper) SetupPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetupPassword(c)
}

// RegisterParticipant operation middleware
func (siw *ServerInterfaceWrapper) RegisterParticipant(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterParticipant(c)
}

// ListProgress operation middleware
func (siw *ServerInterfaceWrapper) ListProgress(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProgressParams

	// ------------- Optional query parameter "team_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "team_id", c.Request.URL.Query(), &params.TeamId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter team_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProgress(c, params)
}

// StaffLogin operation middleware
func (siw *ServerInterfaceWrapper) StaffLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StaffLogin(c)
}

// StaffListTeams operation middleware
func (siw *ServerInterfaceWrapper) StaffListTeams(c *gin.Context) {

	c.Set(StaffBearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StaffListTeams(c)
}

// StaffCreateTeam operation middleware
func (siw *ServerInterfaceWrapper) StaffCreateTeam(c *gin.Context) {

	c.Set(StaffBearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StaffCreateTeam(c)
}

// ListRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListRepositories(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRepositories(c, teamId)
}

// RegisterRepository operation middleware
func (siw *ServerInterfaceWrapper) RegisterRepository(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterRepository(c, teamId)
}

// RemoveRepository operation middleware
func (siw *ServerInterfaceWrapper) RemoveRepository(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "repoId" -------------
	var repoId string

	err = runtime.BindStyledParameterWithOptions("simple", "repoId", c.Param("repoId"), &repoId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter repoId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveRepository(c, teamId, repoId)
}

// UpdateToken operation middleware
func (siw *ServerInterfaceWrapper) UpdateToken(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "repoId" -------------
	var repoId string

	err = runtime.BindStyledParameterWithOptions("simple", "repoId", c.Param("repoId"), &repoId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter repoId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateToken(c, teamId, repoId)
}

// CreateIssue operation middleware
func (siw *ServerInterfaceWrapper) CreateIssue(c *gin.Context) {

	c.Set(InternalTokenAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIssue(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/api/v1/auth/setup", wrapper.SetupPassword)
	router.POST(options.BaseURL+"/api/v1/participants", wrapper.RegisterParticipant)
	router.GET(options.BaseURL+"/api/v1/progress", wrapper.ListProgress)
	router.POST(options.BaseURL+"/api/v1/staff/auth/login", wrapper.StaffLogin)
	router.GET(options.BaseURL+"/api/v1/staff/teams", wrapper.StaffListTeams)
	router.POST(options.BaseURL+"/api/v1/staff/teams", wrapper.StaffCreateTeam)
	router.GET(options.BaseURL+"/api/v1/teams/:teamId/github-repos", wrapper.ListRepositories)
	router.POST(options.BaseURL+"/api/v1/teams/:teamId/github-repos", wrapper.RegisterRepository)
	router.DELETE(options.BaseURL+"/api/v1/teams/:teamId/github-repos/:repoId", wrapper.RemoveRepository)
	router.PUT(options.BaseURL+"/api/v1/teams/:teamId/github-repos/:repoId/token", wrapper.UpdateToken)
	router.POST(options.BaseURL+"/internal/issues", wrapper.CreateIssue)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400JSONResponse ErrorResponse

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login403JSONResponse ErrorResponse

func (response Login403JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SetupPasswordRequestObject struct {
	Body *SetupPasswordJSONRequestBody
}

type SetupPasswordResponseObject interface {
	VisitSetupPasswordResponse(w http.ResponseWriter) error
}

type SetupPassword200JSONResponse MessageResponse

func (response SetupPassword200JSONResponse) VisitSetupPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SetupPassword400JSONResponse ErrorResponse

func (response SetupPassword400JSONResponse) VisitSetupPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterParticipantRequestObject struct {
	Body *RegisterParticipantJSONRequestBody
}

type RegisterParticipantResponseObject interface {
	VisitRegisterParticipantResponse(w http.ResponseWriter) error
}

type RegisterParticipant201JSONResponse RegisterParticipantResponse

func (response RegisterParticipant201JSONResponse) VisitRegisterParticipantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterParticipant400JSONResponse ErrorResponse

func (response RegisterParticipant400JSONResponse) VisitRegisterParticipantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterParticipant403JSONResponse ErrorResponse

func (response RegisterParticipant403JSONResponse) VisitRegisterParticipantResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListProgressRequestObject struct {
	Params ListProgressParams
}

type ListProgressResponseObject interface {
	VisitListProgressResponse(w http.ResponseWriter) error
}

type ListProgress200JSONResponse ProgressListResponse

func (response ListProgress200JSONResponse) VisitListProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProgress500JSONResponse ErrorResponse

func (response ListProgress500JSONResponse) VisitListProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type StaffLoginRequestObject struct {
	Body *StaffLoginJSONRequestBody
}

type StaffLoginResponseObject interface {
	VisitStaffLoginResponse(w http.ResponseWriter) error
}

type StaffLogin200JSONResponse StaffLoginResponse

func (response StaffLogin200JSONResponse) VisitStaffLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StaffLogin400JSONResponse ErrorResponse

func (response StaffLogin400JSONResponse) VisitStaffLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StaffLogin401JSONResponse ErrorResponse

func (response StaffLogin401JSONResponse) VisitStaffLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StaffListTeamsRequestObject struct {
}

type StaffListTeamsResponseObject interface {
	VisitStaffListTeamsResponse(w http.ResponseWriter) error
}

type StaffListTeams200JSONResponse ListTeamsResponse

func (response StaffListTeams200JSONResponse) VisitStaffListTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StaffListTeams500JSONResponse ErrorResponse

func (response StaffListTeams500JSONResponse) VisitStaffListTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type StaffCreateTeamRequestObject struct {
	Body *StaffCreateTeamJSONRequestBody
}

type StaffCreateTeamResponseObject interface {
	VisitStaffCreateTeamResponse(w http.ResponseWriter) error
}

type StaffCreateTeam201JSONResponse CreateTeamResponse

func (response StaffCreateTeam201JSONResponse) VisitStaffCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type StaffCreateTeam400JSONResponse ErrorResponse

func (response StaffCreateTeam400JSONResponse) VisitStaffCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListRepositoriesRequestObject struct {
	TeamId string `json:"teamId"`
}

type ListRepositoriesResponseObject interface {
	VisitListRepositoriesResponse(w http.ResponseWriter) error
}

type ListRepositories200JSONResponse ListReposResponse

func (response ListRepositories200JSONResponse) VisitListRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRepositories400JSONResponse ErrorResponse

func (response ListRepositories400JSONResponse) VisitListRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRepositoryRequestObject struct {
	TeamId string `json:"teamId"`
	Body   *RegisterRepositoryJSONRequestBody
}

type RegisterRepositoryResponseObject interface {
	VisitRegisterRepositoryResponse(w http.ResponseWriter) error
}

type RegisterRepository201JSONResponse MessageResponse

func (response RegisterRepository201JSONResponse) VisitRegisterRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRepository400JSONResponse ErrorResponse

func (response RegisterRepository400JSONResponse) VisitRegisterRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RemoveRepositoryRequestObject struct {
	TeamId string `json:"teamId"`
	RepoId string `json:"repoId"`
}

type RemoveRepositoryResponseObject interface {
	VisitRemoveRepositoryResponse(w http.ResponseWriter) error
}

type RemoveRepository200JSONResponse MessageResponse

func (response RemoveRepository200JSONResponse) VisitRemoveRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RemoveRepository400JSONResponse ErrorResponse

func (response RemoveRepository400JSONResponse) VisitRemoveRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTokenRequestObject struct {
	TeamId string `json:"teamId"`
	RepoId string `json:"repoId"`
	Body   *UpdateTokenJSONRequestBody
}

type UpdateTokenResponseObject interface {
	VisitUpdateTokenResponse(w http.ResponseWriter) error
}

type UpdateToken200JSONResponse MessageResponse

func (response UpdateToken200JSONResponse) VisitUpdateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateToken400JSONResponse ErrorResponse

func (response UpdateToken400JSONResponse) VisitUpdateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssueRequestObject struct {
	Body *CreateIssueJSONRequestBody
}

type CreateIssueResponseObject interface {
	VisitCreateIssueResponse(w http.ResponseWriter) error
}

type CreateIssue201JSONResponse CreateIssueResponse

func (response CreateIssue201JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue400JSONResponse ErrorResponse

func (response CreateIssue400JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate user and get JWT token
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Set password using setup token
	// (POST /api/v1/auth/setup)
	SetupPassword(ctx context.Context, request SetupPasswordRequestObject) (SetupPasswordResponseObject, error)
	// Register a participant in a team (mentor only)
	// (POST /api/v1/participants)
	RegisterParticipant(ctx context.Context, request RegisterParticipantRequestObject) (RegisterParticipantResponseObject, error)
	// List latest progress by team
	// (GET /api/v1/progress)
	ListProgress(ctx context.Context, request ListProgressRequestObject) (ListProgressResponseObject, error)
	// Authenticate staff and get JWT token
	// (POST /api/v1/staff/auth/login)
	StaffLogin(ctx context.Context, request StaffLoginRequestObject) (StaffLoginResponseObject, error)
	// List all teams (staff only)
	// (GET /api/v1/staff/teams)
	StaffListTeams(ctx context.Context, request StaffListTeamsRequestObject) (StaffListTeamsResponseObject, error)
	// Create a new team (staff only)
	// (POST /api/v1/staff/teams)
	StaffCreateTeam(ctx context.Context, request StaffCreateTeamRequestObject) (StaffCreateTeamResponseObject, error)
	// List GitHub repositories for a team
	// (GET /api/v1/teams/{teamId}/github-repos)
	ListRepositories(ctx context.Context, request ListRepositoriesRequestObject) (ListRepositoriesResponseObject, error)
	// Register a GitHub repository for a team
	// (POST /api/v1/teams/{teamId}/github-repos)
	RegisterRepository(ctx context.Context, request RegisterRepositoryRequestObject) (RegisterRepositoryResponseObject, error)
	// Remove a GitHub repository
	// (DELETE /api/v1/teams/{teamId}/github-repos/{repoId})
	RemoveRepository(ctx context.Context, request RemoveRepositoryRequestObject) (RemoveRepositoryResponseObject, error)
	// Update GitHub repository token
	// (PUT /api/v1/teams/{teamId}/github-repos/{repoId}/token)
	UpdateToken(ctx context.Context, request UpdateTokenRequestObject) (UpdateTokenResponseObject, error)
	// Create a GitHub issue (internal)
	// (POST /internal/issues)
	CreateIssue(ctx context.Context, request CreateIssueRequestObject) (CreateIssueResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetupPassword operation middleware
func (sh *strictHandler) SetupPassword(ctx *gin.Context) {
	var request SetupPasswordRequestObject

	var body SetupPasswordJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SetupPassword(ctx, request.(SetupPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetupPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SetupPasswordResponseObject); ok {
		if err := validResponse.VisitSetupPasswordResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterParticipant operation middleware
func (sh *strictHandler) RegisterParticipant(ctx *gin.Context) {
	var request RegisterParticipantRequestObject

	var body RegisterParticipantJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterParticipant(ctx, request.(RegisterParticipantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterParticipant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterParticipantResponseObject); ok {
		if err := validResponse.VisitRegisterParticipantResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProgress operation middleware
func (sh *strictHandler) ListProgress(ctx *gin.Context, params ListProgressParams) {
	var request ListProgressRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProgress(ctx, request.(ListProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProgress")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListProgressResponseObject); ok {
		if err := validResponse.VisitListProgressResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StaffLogin operation middleware
func (sh *strictHandler) StaffLogin(ctx *gin.Context) {
	var request StaffLoginRequestObject

	var body StaffLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StaffLogin(ctx, request.(StaffLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StaffLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StaffLoginResponseObject); ok {
		if err := validResponse.VisitStaffLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StaffListTeams operation middleware
func (sh *strictHandler) StaffListTeams(ctx *gin.Context) {
	var request StaffListTeamsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StaffListTeams(ctx, request.(StaffListTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StaffListTeams")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StaffListTeamsResponseObject); ok {
		if err := validResponse.VisitStaffListTeamsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StaffCreateTeam operation middleware
func (sh *strictHandler) StaffCreateTeam(ctx *gin.Context) {
	var request StaffCreateTeamRequestObject

	var body StaffCreateTeamJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StaffCreateTeam(ctx, request.(StaffCreateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StaffCreateTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StaffCreateTeamResponseObject); ok {
		if err := validResponse.VisitStaffCreateTeamResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRepositories operation middleware
func (sh *strictHandler) ListRepositories(ctx *gin.Context, teamId string) {
	var request ListRepositoriesRequestObject

	request.TeamId = teamId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRepositories(ctx, request.(ListRepositoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRepositories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListRepositoriesResponseObject); ok {
		if err := validResponse.VisitListRepositoriesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterRepository operation middleware
func (sh *strictHandler) RegisterRepository(ctx *gin.Context, teamId string) {
	var request RegisterRepositoryRequestObject

	request.TeamId = teamId

	var body RegisterRepositoryJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterRepository(ctx, request.(RegisterRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterRepository")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterRepositoryResponseObject); ok {
		if err := validResponse.VisitRegisterRepositoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveRepository operation middleware
func (sh *strictHandler) RemoveRepository(ctx *gin.Context, teamId string, repoId string) {
	var request RemoveRepositoryRequestObject

	request.TeamId = teamId
	request.RepoId = repoId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveRepository(ctx, request.(RemoveRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveRepository")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RemoveRepositoryResponseObject); ok {
		if err := validResponse.VisitRemoveRepositoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateToken operation middleware
func (sh *strictHandler) UpdateToken(ctx *gin.Context, teamId string, repoId string) {
	var request UpdateTokenRequestObject

	request.TeamId = teamId
	request.RepoId = repoId

	var body UpdateTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateToken(ctx, request.(UpdateTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateTokenResponseObject); ok {
		if err := validResponse.VisitUpdateTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateIssue operation middleware
func (sh *strictHandler) CreateIssue(ctx *gin.Context) {
	var request CreateIssueRequestObject

	var body CreateIssueJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIssue(ctx, request.(CreateIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateIssueResponseObject); ok {
		if err := validResponse.VisitCreateIssueResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaXW/buBL9KwTvfegFlDi5vffFb22xH+5+IGhSdIEiMGhpbLOVSJUcpasN/N8XJCVL",
	"sklJbmvHBfbJiUkOD2fODA9JP9JYZrkUIFDT6SPV8RoyZv98pYAhzLQu4A18KkCj+TZXMgeFHGyfhUxK",
	"84llDnRKNSouVnQT0XjNhIB0zhNvM3JMwdOyiaiCTwVXkNDp+7aVekzk5ryP6qFy8QFiNEY7gHUuhYZ9",
	"xNw0zwuVDs/edA3PdgcsC3pHsGzEIm2voRlCy0Fgmfn8t4IlndJ/TZpwTqpYTjoWdme3Bnyz/6CUVOGJ",
	"wTQPL85189n/lSFovFFypUDrnoD5GZQzhTzmORMYIlle2Z4vZFIbQ8j0kL9qTC9lUjZ+2y6BKcXKfbIY",
	"iu6A2ofgdQTX+AZy2eMDZZpH4zfGZgjZIGZnNoTJ0Eb3M288pi4HB3A5015ccsVFMN8gYzwNsEXrz1Il",
	"IwhrbbRG9MAIukZ+BOHFUWhQQ656q0GF09Wargz5oP0GWrNVTwHMXIdhT9QdfbN4U2RvqlhmGQj0R2TN",
	"NHhbtKN69f1CyhSYsA3FIuOIkMyZtbmUKjN/0YQhXCDPzO7QvyY3q5sj2uLbMd23YJesoQUnDNlBKbFX",
	"/oZSw87gA/gGVlwjqJumBAXzRKcs/jg3FAruz8Ayf9sOnq6pZuBoiCFXfnWmBDOkhmHKZNBFK47rYjE3",
	"FTIgFiKag9JSsHTO4tjU+FDa7wDbNR0y5Mdelfax26T8LEB5W+z84xSKjayz1B7nA3gLWOQ3Ve0Meren",
	"HEd0pBvrSthbqG+RLZdnsmm0sYRYr02fIdpbQ52KcZjH3CRBiAdLsQNIFOSNtxjuAUitZpzXqmrIUQGJ",
	"2VvfqrZxa6rNtAeFVvckbn2bm73xzgQ+nIxfVsbGF61Omf7K1UdUyfQgt1Qj9oEZRQFxoTiWt4Yw1YkW",
	"mAL1osB189+PtdB4/e7O5I/tbbSJbW1ExxoxNxC5QFCCpdbvtSkuTA9giR3hlkf/uJhVfS/uquyst/+c",
	"/wKllT0mKV9+NayNBbaU1nfu+L1VNeTVGuKPoMiLmxmN6AMozaXBe315dXll95EcBMs5ndLnl1eXz22t",
	"w7X12ITlfPJwPWEFriepqW82yNJxzYSaIZdiltCpE87UhQo0vqyuD2IpsBKKLM9THtsRkw9aiuZSYjDb",
	"22V+0yUEqgLsF46FFvd/r66+9dxbKbKJaAI6VjxH58jbwmbJskiJc9Emov/7hgC6p3UPgJl4YClPiKod",
	"ZOa/Pv38sYIEBHKWaofh+ekw/C6RMGIkv1Qu/4ssY6qkU2oyy8CKGQIx0pEwkZAVIHn97o642mZGdMiu",
	"jdgJk72jhY5Eeq/eOjH5d4+cHs/XCIkGJHqbC2n5ZHkgFYE/c+OgVnQbPtwCklrNkUJzsSI22h4qtC59",
	"dJgMnsPPkSjRcxIcRYzr4yLpI8m2G1HVUEjOo1KeukoVuJaK/wUJWUpFcM01sTe1bdVCp++7euX9/ea+",
	"TeLa/4SRFkkJF4RZa+SZq4VEirT8T5fULYm9At9Ozhtl7W4+WQYISltUVux8KkCVjdZpxHLjqF0Rd3/E",
	"MuW9wvHRsBZFKXfR//9p2ef0IHE35wfF26yMuDMSqQNIFmXDnDq6VlKOEmzNofVYG9jeCf3Eu5fnWP6P",
	"fhup38ISyjJsQEM5Fm7fEbxlxkWnfo2gx5Twe08eHi+YDudZF/ZOid7iwNLUVgNNnrkIVZU/6kv/5h3y",
	"SDVg/yn1xELF89IaCn5su56BKjmYAG6RhBEBn6vtv8OBVmZaikwezccs2UzcjfXF9hUyKAjsMyZHqTiE",
	"REHOcN3VBLP6bNTE+qkkwv5TrCcS20WW20pwXkwYlAg/cfy5WBDVipaVmaxSCtHAGabxwFGDfLyjUfvp",
	"58SlZsRhuUWwczoGfeHJY5dsZYdq44rO5NF8zJKNfWSFFBB87MzkAxyfm5HXkAN4NpXsUJoZ1313HDOg",
	"fQw7mFaT7ZtHXnjqXusV5fsg1bevnJ6HpPO7ZbTwSGGhfmdkdv71FMvWsal+VprYHyb23DW2fgh5VMXe",
	"+W3ok0j27o89fUExHc5XtHteCoOyveKGDT55Vo80wn2z+TsAAP//x5b1ZMcrAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
