// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	BearerAuthScopes        = "bearerAuth.Scopes"
	InternalTokenAuthScopes = "internalTokenAuth.Scopes"
	StaffBearerAuthScopes   = "staffBearerAuth.Scopes"
)

// Defines values for CreateUserRequestRole.
const (
	Mentor      CreateUserRequestRole = "mentor"
	Participant CreateUserRequestRole = "participant"
)

// Valid indicates whether the value is a known member of the CreateUserRequestRole enum.
func (e CreateUserRequestRole) Valid() bool {
	switch e {
	case Mentor:
		return true
	case Participant:
		return true
	default:
		return false
	}
}

// CreateIssueRequest defines model for CreateIssueRequest.
type CreateIssueRequest struct {
	Body      string `json:"body"`
	ChannelId string `json:"channel_id"`
	Title     string `json:"title"`
}

// CreateIssueResponse defines model for CreateIssueResponse.
type CreateIssueResponse struct {
	IssueUrl string `json:"issue_url"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// CreateTeamResponse defines model for CreateTeamResponse.
type CreateTeamResponse struct {
	Team TeamResponse `json:"team"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Email       string                `json:"email"`
	Name        string                `json:"name"`
	Role        CreateUserRequestRole `json:"role"`
	SlackUserId string                `json:"slack_user_id"`
	TeamId      string                `json:"team_id"`
}

// CreateUserRequestRole defines model for CreateUserRequest.Role.
type CreateUserRequestRole string

// CreateUserResponse defines model for CreateUserResponse.
type CreateUserResponse struct {
	SetupUrl string       `json:"setup_url"`
	User     UserResponse `json:"user"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LatestProgressResponse defines model for LatestProgressResponse.
type LatestProgressResponse struct {
	Id             string                 `json:"id"`
	ParticipantId  string                 `json:"participant_id"`
	ProgressBodies []ProgressBodyResponse `json:"progress_bodies"`
}

// ListReposResponse defines model for ListReposResponse.
type ListReposResponse struct {
	Repos []RepoItem `json:"repos"`
}

// ListTeamsResponse defines model for ListTeamsResponse.
type ListTeamsResponse struct {
	Teams []TeamResponse `json:"teams"`
}

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	Users []UserResponse `json:"users"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string       `json:"token"`
	User  UserResponse `json:"user"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// ProgressBodyResponse defines model for ProgressBodyResponse.
type ProgressBodyResponse struct {
	Comment     string    `json:"comment"`
	Phase       string    `json:"phase"`
	Sos         bool      `json:"sos"`
	SubmittedAt time.Time `json:"submitted_at"`
}

// ProgressListResponse defines model for ProgressListResponse.
type ProgressListResponse struct {
	Data []TeamProgressResponse `json:"data"`
}

// RegisterRepoRequest defines model for RegisterRepoRequest.
type RegisterRepoRequest struct {
	GithubRepoUrl       string `json:"github_repo_url"`
	PersonalAccessToken string `json:"personal_access_token"`
}

// RepoItem defines model for RepoItem.
type RepoItem struct {
	Id       string `json:"id"`
	Owner    string `json:"owner"`
	RepoName string `json:"repo_name"`
}

// SetupPasswordRequest defines model for SetupPasswordRequest.
type SetupPasswordRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// StaffLoginRequest defines model for StaffLoginRequest.
type StaffLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// StaffLoginResponse defines model for StaffLoginResponse.
type StaffLoginResponse struct {
	Staff StaffResponse `json:"staff"`
	Token string        `json:"token"`
}

// StaffResponse defines model for StaffResponse.
type StaffResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// TeamProgressResponse defines model for TeamProgressResponse.
type TeamProgressResponse struct {
	LatestProgress *LatestProgressResponse `json:"latest_progress,omitempty"`
	TeamId         string                  `json:"team_id"`
	TeamName       string                  `json:"team_name"`
}

// TeamResponse defines model for TeamResponse.
type TeamResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// UpdateTokenRequest defines model for UpdateTokenRequest.
type UpdateTokenRequest struct {
	PersonalAccessToken string `json:"personal_access_token"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

// ListProgressParams defines parameters for ListProgress.
type ListProgressParams struct {
	TeamId *string `form:"team_id,omitempty" json:"team_id,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SetupPasswordJSONRequestBody defines body for SetupPassword for application/json ContentType.
type SetupPasswordJSONRequestBody = SetupPasswordRequest

// StaffLoginJSONRequestBody defines body for StaffLogin for application/json ContentType.
type StaffLoginJSONRequestBody = StaffLoginRequest

// StaffCreateTeamJSONRequestBody defines body for StaffCreateTeam for application/json ContentType.
type StaffCreateTeamJSONRequestBody = CreateTeamRequest

// StaffCreateUserJSONRequestBody defines body for StaffCreateUser for application/json ContentType.
type StaffCreateUserJSONRequestBody = CreateUserRequest

// RegisterRepositoryJSONRequestBody defines body for RegisterRepository for application/json ContentType.
type RegisterRepositoryJSONRequestBody = RegisterRepoRequest

// UpdateTokenJSONRequestBody defines body for UpdateToken for application/json ContentType.
type UpdateTokenJSONRequestBody = UpdateTokenRequest

// CreateIssueJSONRequestBody defines body for CreateIssue for application/json ContentType.
type CreateIssueJSONRequestBody = CreateIssueRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate user and get JWT token
	// (POST /api/v1/auth/login)
	Login(c *gin.Context)
	// Set password using setup token
	// (POST /api/v1/auth/setup)
	SetupPassword(c *gin.Context)
	// List latest progress by team
	// (GET /api/v1/progress)
	ListProgress(c *gin.Context, params ListProgressParams)
	// Authenticate staff and get JWT token
	// (POST /api/v1/staff/auth/login)
	StaffLogin(c *gin.Context)
	// List all teams (staff only)
	// (GET /api/v1/staff/teams)
	StaffListTeams(c *gin.Context)
	// Create a new team (staff only)
	// (POST /api/v1/staff/teams)
	StaffCreateTeam(c *gin.Context)
	// List all users (staff only)
	// (GET /api/v1/staff/users)
	StaffListUsers(c *gin.Context)
	// Create a new user and generate setup URL (staff only)
	// (POST /api/v1/staff/users)
	StaffCreateUser(c *gin.Context)
	// List GitHub repositories for a team
	// (GET /api/v1/teams/{teamId}/github-repos)
	ListRepositories(c *gin.Context, teamId string)
	// Register a GitHub repository for a team
	// (POST /api/v1/teams/{teamId}/github-repos)
	RegisterRepository(c *gin.Context, teamId string)
	// Remove a GitHub repository
	// (DELETE /api/v1/teams/{teamId}/github-repos/{repoId})
	RemoveRepository(c *gin.Context, teamId string, repoId string)
	// Update GitHub repository token
	// (PUT /api/v1/teams/{teamId}/github-repos/{repoId}/token)
	UpdateToken(c *gin.Context, teamId string, repoId string)
	// Create a GitHub issue (internal)
	// (POST /internal/issues)
	CreateIssue(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// SetupPassword operation middleware
func (siw *ServerInterfaceWrapper) SetupPassword(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetupPassword(c)
}

// ListProgress operation middleware
func (siw *ServerInterfaceWrapper) ListProgress(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProgressParams

	// ------------- Optional query parameter "team_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "team_id", c.Request.URL.Query(), &params.TeamId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter team_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProgress(c, params)
}

// StaffLogin operation middleware
func (siw *ServerInterfaceWrapper) StaffLogin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StaffLogin(c)
}

// StaffListTeams operation middleware
func (siw *ServerInterfaceWrapper) StaffListTeams(c *gin.Context) {

	c.Set(StaffBearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StaffListTeams(c)
}

// StaffCreateTeam operation middleware
func (siw *ServerInterfaceWrapper) StaffCreateTeam(c *gin.Context) {

	c.Set(StaffBearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StaffCreateTeam(c)
}

// StaffListUsers operation middleware
func (siw *ServerInterfaceWrapper) StaffListUsers(c *gin.Context) {

	c.Set(StaffBearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StaffListUsers(c)
}

// StaffCreateUser operation middleware
func (siw *ServerInterfaceWrapper) StaffCreateUser(c *gin.Context) {

	c.Set(StaffBearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StaffCreateUser(c)
}

// ListRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListRepositories(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRepositories(c, teamId)
}

// RegisterRepository operation middleware
func (siw *ServerInterfaceWrapper) RegisterRepository(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterRepository(c, teamId)
}

// RemoveRepository operation middleware
func (siw *ServerInterfaceWrapper) RemoveRepository(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "repoId" -------------
	var repoId string

	err = runtime.BindStyledParameterWithOptions("simple", "repoId", c.Param("repoId"), &repoId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter repoId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveRepository(c, teamId, repoId)
}

// UpdateToken operation middleware
func (siw *ServerInterfaceWrapper) UpdateToken(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "repoId" -------------
	var repoId string

	err = runtime.BindStyledParameterWithOptions("simple", "repoId", c.Param("repoId"), &repoId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter repoId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateToken(c, teamId, repoId)
}

// CreateIssue operation middleware
func (siw *ServerInterfaceWrapper) CreateIssue(c *gin.Context) {

	c.Set(InternalTokenAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIssue(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/api/v1/auth/setup", wrapper.SetupPassword)
	router.GET(options.BaseURL+"/api/v1/progress", wrapper.ListProgress)
	router.POST(options.BaseURL+"/api/v1/staff/auth/login", wrapper.StaffLogin)
	router.GET(options.BaseURL+"/api/v1/staff/teams", wrapper.StaffListTeams)
	router.POST(options.BaseURL+"/api/v1/staff/teams", wrapper.StaffCreateTeam)
	router.GET(options.BaseURL+"/api/v1/staff/users", wrapper.StaffListUsers)
	router.POST(options.BaseURL+"/api/v1/staff/users", wrapper.StaffCreateUser)
	router.GET(options.BaseURL+"/api/v1/teams/:teamId/github-repos", wrapper.ListRepositories)
	router.POST(options.BaseURL+"/api/v1/teams/:teamId/github-repos", wrapper.RegisterRepository)
	router.DELETE(options.BaseURL+"/api/v1/teams/:teamId/github-repos/:repoId", wrapper.RemoveRepository)
	router.PUT(options.BaseURL+"/api/v1/teams/:teamId/github-repos/:repoId/token", wrapper.UpdateToken)
	router.POST(options.BaseURL+"/internal/issues", wrapper.CreateIssue)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400JSONResponse ErrorResponse

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login403JSONResponse ErrorResponse

func (response Login403JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SetupPasswordRequestObject struct {
	Body *SetupPasswordJSONRequestBody
}

type SetupPasswordResponseObject interface {
	VisitSetupPasswordResponse(w http.ResponseWriter) error
}

type SetupPassword200JSONResponse MessageResponse

func (response SetupPassword200JSONResponse) VisitSetupPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SetupPassword400JSONResponse ErrorResponse

func (response SetupPassword400JSONResponse) VisitSetupPasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListProgressRequestObject struct {
	Params ListProgressParams
}

type ListProgressResponseObject interface {
	VisitListProgressResponse(w http.ResponseWriter) error
}

type ListProgress200JSONResponse ProgressListResponse

func (response ListProgress200JSONResponse) VisitListProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProgress500JSONResponse ErrorResponse

func (response ListProgress500JSONResponse) VisitListProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type StaffLoginRequestObject struct {
	Body *StaffLoginJSONRequestBody
}

type StaffLoginResponseObject interface {
	VisitStaffLoginResponse(w http.ResponseWriter) error
}

type StaffLogin200JSONResponse StaffLoginResponse

func (response StaffLogin200JSONResponse) VisitStaffLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StaffLogin400JSONResponse ErrorResponse

func (response StaffLogin400JSONResponse) VisitStaffLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StaffLogin401JSONResponse ErrorResponse

func (response StaffLogin401JSONResponse) VisitStaffLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type StaffListTeamsRequestObject struct {
}

type StaffListTeamsResponseObject interface {
	VisitStaffListTeamsResponse(w http.ResponseWriter) error
}

type StaffListTeams200JSONResponse ListTeamsResponse

func (response StaffListTeams200JSONResponse) VisitStaffListTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StaffListTeams500JSONResponse ErrorResponse

func (response StaffListTeams500JSONResponse) VisitStaffListTeamsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type StaffCreateTeamRequestObject struct {
	Body *StaffCreateTeamJSONRequestBody
}

type StaffCreateTeamResponseObject interface {
	VisitStaffCreateTeamResponse(w http.ResponseWriter) error
}

type StaffCreateTeam201JSONResponse CreateTeamResponse

func (response StaffCreateTeam201JSONResponse) VisitStaffCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type StaffCreateTeam400JSONResponse ErrorResponse

func (response StaffCreateTeam400JSONResponse) VisitStaffCreateTeamResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type StaffListUsersRequestObject struct {
}

type StaffListUsersResponseObject interface {
	VisitStaffListUsersResponse(w http.ResponseWriter) error
}

type StaffListUsers200JSONResponse ListUsersResponse

func (response StaffListUsers200JSONResponse) VisitStaffListUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type StaffListUsers500JSONResponse ErrorResponse

func (response StaffListUsers500JSONResponse) VisitStaffListUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type StaffCreateUserRequestObject struct {
	Body *StaffCreateUserJSONRequestBody
}

type StaffCreateUserResponseObject interface {
	VisitStaffCreateUserResponse(w http.ResponseWriter) error
}

type StaffCreateUser201JSONResponse CreateUserResponse

func (response StaffCreateUser201JSONResponse) VisitStaffCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type StaffCreateUser400JSONResponse ErrorResponse

func (response StaffCreateUser400JSONResponse) VisitStaffCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListRepositoriesRequestObject struct {
	TeamId string `json:"teamId"`
}

type ListRepositoriesResponseObject interface {
	VisitListRepositoriesResponse(w http.ResponseWriter) error
}

type ListRepositories200JSONResponse ListReposResponse

func (response ListRepositories200JSONResponse) VisitListRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRepositories400JSONResponse ErrorResponse

func (response ListRepositories400JSONResponse) VisitListRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRepositoryRequestObject struct {
	TeamId string `json:"teamId"`
	Body   *RegisterRepositoryJSONRequestBody
}

type RegisterRepositoryResponseObject interface {
	VisitRegisterRepositoryResponse(w http.ResponseWriter) error
}

type RegisterRepository201JSONResponse MessageResponse

func (response RegisterRepository201JSONResponse) VisitRegisterRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRepository400JSONResponse ErrorResponse

func (response RegisterRepository400JSONResponse) VisitRegisterRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RemoveRepositoryRequestObject struct {
	TeamId string `json:"teamId"`
	RepoId string `json:"repoId"`
}

type RemoveRepositoryResponseObject interface {
	VisitRemoveRepositoryResponse(w http.ResponseWriter) error
}

type RemoveRepository200JSONResponse MessageResponse

func (response RemoveRepository200JSONResponse) VisitRemoveRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RemoveRepository400JSONResponse ErrorResponse

func (response RemoveRepository400JSONResponse) VisitRemoveRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTokenRequestObject struct {
	TeamId string `json:"teamId"`
	RepoId string `json:"repoId"`
	Body   *UpdateTokenJSONRequestBody
}

type UpdateTokenResponseObject interface {
	VisitUpdateTokenResponse(w http.ResponseWriter) error
}

type UpdateToken200JSONResponse MessageResponse

func (response UpdateToken200JSONResponse) VisitUpdateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateToken400JSONResponse ErrorResponse

func (response UpdateToken400JSONResponse) VisitUpdateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssueRequestObject struct {
	Body *CreateIssueJSONRequestBody
}

type CreateIssueResponseObject interface {
	VisitCreateIssueResponse(w http.ResponseWriter) error
}

type CreateIssue201JSONResponse CreateIssueResponse

func (response CreateIssue201JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue400JSONResponse ErrorResponse

func (response CreateIssue400JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate user and get JWT token
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Set password using setup token
	// (POST /api/v1/auth/setup)
	SetupPassword(ctx context.Context, request SetupPasswordRequestObject) (SetupPasswordResponseObject, error)
	// List latest progress by team
	// (GET /api/v1/progress)
	ListProgress(ctx context.Context, request ListProgressRequestObject) (ListProgressResponseObject, error)
	// Authenticate staff and get JWT token
	// (POST /api/v1/staff/auth/login)
	StaffLogin(ctx context.Context, request StaffLoginRequestObject) (StaffLoginResponseObject, error)
	// List all teams (staff only)
	// (GET /api/v1/staff/teams)
	StaffListTeams(ctx context.Context, request StaffListTeamsRequestObject) (StaffListTeamsResponseObject, error)
	// Create a new team (staff only)
	// (POST /api/v1/staff/teams)
	StaffCreateTeam(ctx context.Context, request StaffCreateTeamRequestObject) (StaffCreateTeamResponseObject, error)
	// List all users (staff only)
	// (GET /api/v1/staff/users)
	StaffListUsers(ctx context.Context, request StaffListUsersRequestObject) (StaffListUsersResponseObject, error)
	// Create a new user and generate setup URL (staff only)
	// (POST /api/v1/staff/users)
	StaffCreateUser(ctx context.Context, request StaffCreateUserRequestObject) (StaffCreateUserResponseObject, error)
	// List GitHub repositories for a team
	// (GET /api/v1/teams/{teamId}/github-repos)
	ListRepositories(ctx context.Context, request ListRepositoriesRequestObject) (ListRepositoriesResponseObject, error)
	// Register a GitHub repository for a team
	// (POST /api/v1/teams/{teamId}/github-repos)
	RegisterRepository(ctx context.Context, request RegisterRepositoryRequestObject) (RegisterRepositoryResponseObject, error)
	// Remove a GitHub repository
	// (DELETE /api/v1/teams/{teamId}/github-repos/{repoId})
	RemoveRepository(ctx context.Context, request RemoveRepositoryRequestObject) (RemoveRepositoryResponseObject, error)
	// Update GitHub repository token
	// (PUT /api/v1/teams/{teamId}/github-repos/{repoId}/token)
	UpdateToken(ctx context.Context, request UpdateTokenRequestObject) (UpdateTokenResponseObject, error)
	// Create a GitHub issue (internal)
	// (POST /internal/issues)
	CreateIssue(ctx context.Context, request CreateIssueRequestObject) (CreateIssueResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SetupPassword operation middleware
func (sh *strictHandler) SetupPassword(ctx *gin.Context) {
	var request SetupPasswordRequestObject

	var body SetupPasswordJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SetupPassword(ctx, request.(SetupPasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetupPassword")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SetupPasswordResponseObject); ok {
		if err := validResponse.VisitSetupPasswordResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProgress operation middleware
func (sh *strictHandler) ListProgress(ctx *gin.Context, params ListProgressParams) {
	var request ListProgressRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProgress(ctx, request.(ListProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProgress")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListProgressResponseObject); ok {
		if err := validResponse.VisitListProgressResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StaffLogin operation middleware
func (sh *strictHandler) StaffLogin(ctx *gin.Context) {
	var request StaffLoginRequestObject

	var body StaffLoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StaffLogin(ctx, request.(StaffLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StaffLogin")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StaffLoginResponseObject); ok {
		if err := validResponse.VisitStaffLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StaffListTeams operation middleware
func (sh *strictHandler) StaffListTeams(ctx *gin.Context) {
	var request StaffListTeamsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StaffListTeams(ctx, request.(StaffListTeamsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StaffListTeams")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StaffListTeamsResponseObject); ok {
		if err := validResponse.VisitStaffListTeamsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StaffCreateTeam operation middleware
func (sh *strictHandler) StaffCreateTeam(ctx *gin.Context) {
	var request StaffCreateTeamRequestObject

	var body StaffCreateTeamJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StaffCreateTeam(ctx, request.(StaffCreateTeamRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StaffCreateTeam")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StaffCreateTeamResponseObject); ok {
		if err := validResponse.VisitStaffCreateTeamResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StaffListUsers operation middleware
func (sh *strictHandler) StaffListUsers(ctx *gin.Context) {
	var request StaffListUsersRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StaffListUsers(ctx, request.(StaffListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StaffListUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StaffListUsersResponseObject); ok {
		if err := validResponse.VisitStaffListUsersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// StaffCreateUser operation middleware
func (sh *strictHandler) StaffCreateUser(ctx *gin.Context) {
	var request StaffCreateUserRequestObject

	var body StaffCreateUserJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StaffCreateUser(ctx, request.(StaffCreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StaffCreateUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(StaffCreateUserResponseObject); ok {
		if err := validResponse.VisitStaffCreateUserResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRepositories operation middleware
func (sh *strictHandler) ListRepositories(ctx *gin.Context, teamId string) {
	var request ListRepositoriesRequestObject

	request.TeamId = teamId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRepositories(ctx, request.(ListRepositoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRepositories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListRepositoriesResponseObject); ok {
		if err := validResponse.VisitListRepositoriesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterRepository operation middleware
func (sh *strictHandler) RegisterRepository(ctx *gin.Context, teamId string) {
	var request RegisterRepositoryRequestObject

	request.TeamId = teamId

	var body RegisterRepositoryJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterRepository(ctx, request.(RegisterRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterRepository")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterRepositoryResponseObject); ok {
		if err := validResponse.VisitRegisterRepositoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveRepository operation middleware
func (sh *strictHandler) RemoveRepository(ctx *gin.Context, teamId string, repoId string) {
	var request RemoveRepositoryRequestObject

	request.TeamId = teamId
	request.RepoId = repoId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveRepository(ctx, request.(RemoveRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveRepository")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RemoveRepositoryResponseObject); ok {
		if err := validResponse.VisitRemoveRepositoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateToken operation middleware
func (sh *strictHandler) UpdateToken(ctx *gin.Context, teamId string, repoId string) {
	var request UpdateTokenRequestObject

	request.TeamId = teamId
	request.RepoId = repoId

	var body UpdateTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateToken(ctx, request.(UpdateTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateTokenResponseObject); ok {
		if err := validResponse.VisitUpdateTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateIssue operation middleware
func (sh *strictHandler) CreateIssue(ctx *gin.Context) {
	var request CreateIssueRequestObject

	var body CreateIssueJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIssue(ctx, request.(CreateIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateIssueResponseObject); ok {
		if err := validResponse.VisitCreateIssueResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW2/buBL+KwTPeegBlDg5PefFb22xF3e7iyIXdIGiMGhpbLOVSJWk0jUC//fFkJIl",
	"WaQkd+PEWeyTE4scfnP7ZjT0PY1llksBwmg6vac6XkPG7J9vFDADM60LuIKvBWiD3+ZK5qAMB7tmIZMN",
	"fppNDnRKtVFcrOg2ovGaCQHpnCfex4abFDxPthFV8LXgChI6/diUUu2J3JmfomqrXHyG2KDQFmCdS6Gh",
	"i5jj43mh0uHT66Xh026AZUHrCJaNUNKuGjohpI4BluHnvxUs6ZT+a1K7c1L6ctKSsH+6FRA+/VaDCuoH",
	"GeOp178BzSOqpPM7iCLD43OmDI95zoShEc1AGKkacOqNOmXxl3mhQQVjCljmf7ancltUCTYqtSkh1uKG",
	"bBPyjAZT5IFAiyiePuS3lvx9JayAqHGKD+cPSskeiICPh+3llvnkv2MGtHmv5EqB1j1J5/dYw/khp+al",
	"7PlCJpUwA5kesl2F6bVMNrUNdyowpdimm/AYDXuguhC8huDaXEEue2yg8PFo/ChsZiAbxOzEhjBh6ut+",
	"9hiPqc0jA7ic6BAuDO0eXBjc43G182QAlxPtxSVXXHwH1+VM629SjSCeimF2O3pgBF0mv4A4DqU40aUg",
	"H7RfQWu26imumVswbIlqoe8Ub+p2joplhtXC75E10/7yo10Klt8vpEyBCfugWGTcGEjmzMpcSpXhXzRh",
	"Bs4MtxWiXyd3qjsj2uHbE92nsCORkMIJM+ygVO3Q8lBq2BN8AK9gxbXByMllMEFW3KyLxRz5KFj1clBa",
	"CpbOWRwjo4aCeQ/YvuiQID/2kkjHFiX5TYDy9y54/riezhYOJ6m5zwfwGiv4+5IRgtbtIZmIjjRjld+9",
	"9HNt2HJ5IlTYxBJss3DNUDpYQa08OMxi7pAgxIMbnwOCKBg33hTvAEhthzavepghQwUaut7uunw2TqdK",
	"THNTSLsnMettjox/g44PJ+P30dh40up/szhM+/qda6xZyh1dYFgnIS4UN5trDJhyBgBMgXpVmHX9349V",
	"+Xz74Qbzx67Gimuf1qV0bUyOELkwoARLrd0rUVzgCmCJ3eHUo7+fzcq1ZzdldlZFLee/wMYWc0zK138Z",
	"1tYCW0prOzew2NVq8mYN8RdQ5NX7GY3oHSjNJeK9PL84v7B1JAfBck6n9OX5xflLy3VmbS02YTmf3F1O",
	"WGHWkxT5zTpZulhDVzPDpZgldOraQepcBdq8LgcusRSmbH9Ynqc8tjsmn7UU9RhnMNubNL9tB4RRBdgv",
	"XBRa3P+9uHjos3et6DaiCehY8dw4Q14XNkuWRUqcibYR/d8DAmi/G3sAzMQdS3lCVGUgPP/y8c+PFSQg",
	"DGepdhhePh6G36QhjJRjGZv/RZYxtaFTipmFsGJmgOArA2EiISsw5O2HG+K4DXe0gt2OK8LB3uqFjhT0",
	"3n7rkYN//0XKY/kKIdFgiN7lQrp5sjyQisAfORqo4d06Hq7BkKqbI4XmYkWstz2h0OxGVuAjPV43IW4k",
	"wzIwdibwsawLXwtQm7os1H1FrfV+vft0RI963+F8bq3qR8odpfz/cV3pSidxI71mQbeWbZbyj5/QYLV/",
	"UTPi2klSOZAsNsQOkJvetdV3VG2r+/tj5XrnZeaRE93zBvNPqRtZ6sLVxkbYQLlxUbgbcHppxnmnGpPS",
	"Y3Y7nVmsxwq44DR5odNQe8mBpallA01eOA9JkW7+Y+cC4fSvL7mOxAHde7pRHHB5FAADzo/t0uTp8//g",
	"AHBKEkYEfLNBsBcDnczcjfj7M9NeFBw7M9u3ER774ILnnpnW4Idn5q0uZ5jHyszmDfOTZObenYjf+X+T",
	"zGy8pwl0OJQ9+u3Vu3DCWk6f3OPHLNlO3DT+bHefGezg7YUoN1JxCHXxOTPrdhM/q9776hB4qp6+e6nr",
	"cdBOyc2OIE4rQAZ7+p+4+blYENXwFllKRVjZ2odIonkr5CxwVCc/PP/4rrUemYFGDAIaAaZKwKfIQ31h",
	"VhmasE6wbVqhNo50Jvf4MUu29loUUjDgi85M3sHxYzPyCnIAT4bJDg0zNN2zizEE7Yuwg8NqsrvPyQsP",
	"7zVuiJ5HUD08c3ouyU5vgmrhkcJCfWbB7OzrIcvGnKO6MpvYn6nq8JSt8bPYozbyrV8KP0kn3/7pr88p",
	"uOB0e3nPLWiwmy9jwzqfvKh2YuO+3f4ZAAD///4oFyrVLQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
