// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	BearerAuthScopes        = "bearerAuth.Scopes"
	InternalTokenAuthScopes = "internalTokenAuth.Scopes"
)

// CreateIssueRequest defines model for CreateIssueRequest.
type CreateIssueRequest struct {
	Body      string `json:"body"`
	ChannelId string `json:"channel_id"`
	Title     string `json:"title"`
}

// CreateIssueResponse defines model for CreateIssueResponse.
type CreateIssueResponse struct {
	IssueUrl string `json:"issue_url"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// LatestProgressResponse defines model for LatestProgressResponse.
type LatestProgressResponse struct {
	Id             string                 `json:"id"`
	ParticipantId  string                 `json:"participant_id"`
	ProgressBodies []ProgressBodyResponse `json:"progress_bodies"`
}

// ListReposResponse defines model for ListReposResponse.
type ListReposResponse struct {
	Repos []RepoItem `json:"repos"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Token string       `json:"token"`
	User  UserResponse `json:"user"`
}

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	Message string `json:"message"`
}

// ProgressBodyResponse defines model for ProgressBodyResponse.
type ProgressBodyResponse struct {
	Comment     string    `json:"comment"`
	Phase       string    `json:"phase"`
	Sos         bool      `json:"sos"`
	SubmittedAt time.Time `json:"submitted_at"`
}

// ProgressListResponse defines model for ProgressListResponse.
type ProgressListResponse struct {
	Data []TeamProgressResponse `json:"data"`
}

// RegisterRepoRequest defines model for RegisterRepoRequest.
type RegisterRepoRequest struct {
	GithubRepoUrl       string `json:"github_repo_url"`
	PersonalAccessToken string `json:"personal_access_token"`
}

// RepoItem defines model for RepoItem.
type RepoItem struct {
	Id       string `json:"id"`
	Owner    string `json:"owner"`
	RepoName string `json:"repo_name"`
}

// TeamProgressResponse defines model for TeamProgressResponse.
type TeamProgressResponse struct {
	LatestProgress *LatestProgressResponse `json:"latest_progress,omitempty"`
	TeamId         string                  `json:"team_id"`
	TeamName       string                  `json:"team_name"`
}

// UpdateTokenRequest defines model for UpdateTokenRequest.
type UpdateTokenRequest struct {
	PersonalAccessToken string `json:"personal_access_token"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	Role string `json:"role"`
}

// ListProgressParams defines parameters for ListProgress.
type ListProgressParams struct {
	TeamId *string `form:"team_id,omitempty" json:"team_id,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterRepositoryJSONRequestBody defines body for RegisterRepository for application/json ContentType.
type RegisterRepositoryJSONRequestBody = RegisterRepoRequest

// UpdateTokenJSONRequestBody defines body for UpdateToken for application/json ContentType.
type UpdateTokenJSONRequestBody = UpdateTokenRequest

// CreateIssueJSONRequestBody defines body for CreateIssue for application/json ContentType.
type CreateIssueJSONRequestBody = CreateIssueRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate user and get JWT token
	// (POST /api/v1/auth/login)
	Login(c *gin.Context)
	// List latest progress by team
	// (GET /api/v1/progress)
	ListProgress(c *gin.Context, params ListProgressParams)
	// List GitHub repositories for a team
	// (GET /api/v1/teams/{teamId}/github-repos)
	ListRepositories(c *gin.Context, teamId string)
	// Register a GitHub repository for a team
	// (POST /api/v1/teams/{teamId}/github-repos)
	RegisterRepository(c *gin.Context, teamId string)
	// Remove a GitHub repository
	// (DELETE /api/v1/teams/{teamId}/github-repos/{repoId})
	RemoveRepository(c *gin.Context, teamId string, repoId string)
	// Update GitHub repository token
	// (PUT /api/v1/teams/{teamId}/github-repos/{repoId}/token)
	UpdateToken(c *gin.Context, teamId string, repoId string)
	// Create a GitHub issue (internal)
	// (POST /internal/issues)
	CreateIssue(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// ListProgress operation middleware
func (siw *ServerInterfaceWrapper) ListProgress(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProgressParams

	// ------------- Optional query parameter "team_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "team_id", c.Request.URL.Query(), &params.TeamId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter team_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProgress(c, params)
}

// ListRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListRepositories(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListRepositories(c, teamId)
}

// RegisterRepository operation middleware
func (siw *ServerInterfaceWrapper) RegisterRepository(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterRepository(c, teamId)
}

// RemoveRepository operation middleware
func (siw *ServerInterfaceWrapper) RemoveRepository(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "repoId" -------------
	var repoId string

	err = runtime.BindStyledParameterWithOptions("simple", "repoId", c.Param("repoId"), &repoId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter repoId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveRepository(c, teamId, repoId)
}

// UpdateToken operation middleware
func (siw *ServerInterfaceWrapper) UpdateToken(c *gin.Context) {

	var err error

	// ------------- Path parameter "teamId" -------------
	var teamId string

	err = runtime.BindStyledParameterWithOptions("simple", "teamId", c.Param("teamId"), &teamId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter teamId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "repoId" -------------
	var repoId string

	err = runtime.BindStyledParameterWithOptions("simple", "repoId", c.Param("repoId"), &repoId, runtime.BindStyledParameterOptions{Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter repoId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateToken(c, teamId, repoId)
}

// CreateIssue operation middleware
func (siw *ServerInterfaceWrapper) CreateIssue(c *gin.Context) {

	c.Set(InternalTokenAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateIssue(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	router.GET(options.BaseURL+"/api/v1/progress", wrapper.ListProgress)
	router.GET(options.BaseURL+"/api/v1/teams/:teamId/github-repos", wrapper.ListRepositories)
	router.POST(options.BaseURL+"/api/v1/teams/:teamId/github-repos", wrapper.RegisterRepository)
	router.DELETE(options.BaseURL+"/api/v1/teams/:teamId/github-repos/:repoId", wrapper.RemoveRepository)
	router.PUT(options.BaseURL+"/api/v1/teams/:teamId/github-repos/:repoId/token", wrapper.UpdateToken)
	router.POST(options.BaseURL+"/internal/issues", wrapper.CreateIssue)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login400JSONResponse ErrorResponse

func (response Login400JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login403JSONResponse ErrorResponse

func (response Login403JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ListProgressRequestObject struct {
	Params ListProgressParams
}

type ListProgressResponseObject interface {
	VisitListProgressResponse(w http.ResponseWriter) error
}

type ListProgress200JSONResponse ProgressListResponse

func (response ListProgress200JSONResponse) VisitListProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListProgress500JSONResponse ErrorResponse

func (response ListProgress500JSONResponse) VisitListProgressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListRepositoriesRequestObject struct {
	TeamId string `json:"teamId"`
}

type ListRepositoriesResponseObject interface {
	VisitListRepositoriesResponse(w http.ResponseWriter) error
}

type ListRepositories200JSONResponse ListReposResponse

func (response ListRepositories200JSONResponse) VisitListRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListRepositories400JSONResponse ErrorResponse

func (response ListRepositories400JSONResponse) VisitListRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRepositoryRequestObject struct {
	TeamId string `json:"teamId"`
	Body   *RegisterRepositoryJSONRequestBody
}

type RegisterRepositoryResponseObject interface {
	VisitRegisterRepositoryResponse(w http.ResponseWriter) error
}

type RegisterRepository201JSONResponse MessageResponse

func (response RegisterRepository201JSONResponse) VisitRegisterRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterRepository400JSONResponse ErrorResponse

func (response RegisterRepository400JSONResponse) VisitRegisterRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RemoveRepositoryRequestObject struct {
	TeamId string `json:"teamId"`
	RepoId string `json:"repoId"`
}

type RemoveRepositoryResponseObject interface {
	VisitRemoveRepositoryResponse(w http.ResponseWriter) error
}

type RemoveRepository200JSONResponse MessageResponse

func (response RemoveRepository200JSONResponse) VisitRemoveRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RemoveRepository400JSONResponse ErrorResponse

func (response RemoveRepository400JSONResponse) VisitRemoveRepositoryResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTokenRequestObject struct {
	TeamId string `json:"teamId"`
	RepoId string `json:"repoId"`
	Body   *UpdateTokenJSONRequestBody
}

type UpdateTokenResponseObject interface {
	VisitUpdateTokenResponse(w http.ResponseWriter) error
}

type UpdateToken200JSONResponse MessageResponse

func (response UpdateToken200JSONResponse) VisitUpdateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateToken400JSONResponse ErrorResponse

func (response UpdateToken400JSONResponse) VisitUpdateTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssueRequestObject struct {
	Body *CreateIssueJSONRequestBody
}

type CreateIssueResponseObject interface {
	VisitCreateIssueResponse(w http.ResponseWriter) error
}

type CreateIssue201JSONResponse CreateIssueResponse

func (response CreateIssue201JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateIssue400JSONResponse ErrorResponse

func (response CreateIssue400JSONResponse) VisitCreateIssueResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Authenticate user and get JWT token
	// (POST /api/v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// List latest progress by team
	// (GET /api/v1/progress)
	ListProgress(ctx context.Context, request ListProgressRequestObject) (ListProgressResponseObject, error)
	// List GitHub repositories for a team
	// (GET /api/v1/teams/{teamId}/github-repos)
	ListRepositories(ctx context.Context, request ListRepositoriesRequestObject) (ListRepositoriesResponseObject, error)
	// Register a GitHub repository for a team
	// (POST /api/v1/teams/{teamId}/github-repos)
	RegisterRepository(ctx context.Context, request RegisterRepositoryRequestObject) (RegisterRepositoryResponseObject, error)
	// Remove a GitHub repository
	// (DELETE /api/v1/teams/{teamId}/github-repos/{repoId})
	RemoveRepository(ctx context.Context, request RemoveRepositoryRequestObject) (RemoveRepositoryResponseObject, error)
	// Update GitHub repository token
	// (PUT /api/v1/teams/{teamId}/github-repos/{repoId}/token)
	UpdateToken(ctx context.Context, request UpdateTokenRequestObject) (UpdateTokenResponseObject, error)
	// Create a GitHub issue (internal)
	// (POST /internal/issues)
	CreateIssue(ctx context.Context, request CreateIssueRequestObject) (CreateIssueResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProgress operation middleware
func (sh *strictHandler) ListProgress(ctx *gin.Context, params ListProgressParams) {
	var request ListProgressRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProgress(ctx, request.(ListProgressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProgress")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListProgressResponseObject); ok {
		if err := validResponse.VisitListProgressResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRepositories operation middleware
func (sh *strictHandler) ListRepositories(ctx *gin.Context, teamId string) {
	var request ListRepositoriesRequestObject

	request.TeamId = teamId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListRepositories(ctx, request.(ListRepositoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRepositories")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListRepositoriesResponseObject); ok {
		if err := validResponse.VisitListRepositoriesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RegisterRepository operation middleware
func (sh *strictHandler) RegisterRepository(ctx *gin.Context, teamId string) {
	var request RegisterRepositoryRequestObject

	request.TeamId = teamId

	var body RegisterRepositoryJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterRepository(ctx, request.(RegisterRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterRepository")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RegisterRepositoryResponseObject); ok {
		if err := validResponse.VisitRegisterRepositoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveRepository operation middleware
func (sh *strictHandler) RemoveRepository(ctx *gin.Context, teamId string, repoId string) {
	var request RemoveRepositoryRequestObject

	request.TeamId = teamId
	request.RepoId = repoId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveRepository(ctx, request.(RemoveRepositoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveRepository")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RemoveRepositoryResponseObject); ok {
		if err := validResponse.VisitRemoveRepositoryResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateToken operation middleware
func (sh *strictHandler) UpdateToken(ctx *gin.Context, teamId string, repoId string) {
	var request UpdateTokenRequestObject

	request.TeamId = teamId
	request.RepoId = repoId

	var body UpdateTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateToken(ctx, request.(UpdateTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateTokenResponseObject); ok {
		if err := validResponse.VisitUpdateTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateIssue operation middleware
func (sh *strictHandler) CreateIssue(ctx *gin.Context) {
	var request CreateIssueRequestObject

	var body CreateIssueJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateIssue(ctx, request.(CreateIssueRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateIssue")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateIssueResponseObject); ok {
		if err := validResponse.VisitCreateIssueResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZbW/bNhD+KwS3DxugRMmyffG3ttiLuxcUaYoOCAKDli42W4lkyFMKI/B/H47Um23K",
	"VobEbT5ZEcm7h3cPn+NFDzzTpdEKFDo+eeAuW0Ip/OMbCwJh6lwFl3BXgUN6a6w2YFGCnzPX+Yp+cWWA",
	"T7hDK9WCrxOeLYVSUMxkHh1GiQVERtYJt3BXSQs5n1z3rTRrkuDzJmmW6vknyJCMbgB2RisHu4glDc8q",
	"Wxz23k2NefvVWm2H/QANH/YRpsXs/yUQHL6zemHBuT0bikfYCIsyk0YoHEqCqW3P5jpvjCGU/uF7C7d8",
	"wr9LO3qkNTfSBtNrna9aXOt2C8JasdoNJqVwC9QuhGggpMNLMHpPDCwNj8ZPxqYI5UHMwWwUk15INXgq",
	"oBSyGMiKc1+0zUcQw9vordgDYygsqD+DiuKoHNhDYfrgoOP3NrxgujYUg/Y3OCcWew5iGSYcjkQzMeYl",
	"SsUdV5kuS1AYz8hSOIiOuECp+v1c6wKE8gPVvJSIkM+Et3mrbUlPPBcIJyhLUqn9ewpeg4+kxbdlet+G",
	"w6EY2nAuUIw+Dlcgyh2ZOXQ0vIcYwEtYSIfEHKMHD8hC4rKaz+h8DUhxwg1Yp5UoZiLLSCGGyLwFbNv0",
	"kKE49loYxoqs/qLARke8fyXKEfz2Qhgs9dfFAEZTtQO28JVj1mjrofwPFBpiAIhysILT2LgNNmb6i2K7",
	"+2DoAF1RegaZ8z9ZMZ4DG6o3lgcDcUi41cVYBngb9YpdYCQ7kFVW4uo95a2+foGwYF9VuOz++q1Ro7cf",
	"r0hR/GwSMD/aKdMS0RBEqRCsEoWPe2NKKpoBIvcrwvb4vyfTeu7JVS3/jUYY+SeQSHh7t9pvOVzxWsVi",
	"b5aQfQbLXr2b8oTfg3VSk5vz07PTM3+aDChhJJ/wi9Oz0wtf/HDpN5oKI9P781RUuEwLqno+NzpQhDIk",
	"UGo1zfkkFEUeIgwOX9dX1EwrrIuAMKaQmV+RfnJadRffg2elX/fXm3lEW4F/Ecjjcf90dvbUvtuCvE54",
	"Di6z0mAI5PvKk/u2KlgI0TrhPz8hgM0bbwTAVN2LQubMNgEi/+fH959ZyEGhFIULGC6Oh+EfjUwwKufa",
	"hmNblaWwKz7hdLgIViYQGF2cmFA5WwCytx+vWJAkWtGQvS/gC4gxXXa6HW7XogQE6/jkuj7DdxXYVXeE",
	"OynutrutTTfPyOHo9SUSxVY0Chl49MtxeRxkjoXurC++PrJ92b2+oYB1SaadsVCBWZNANl8xivxGdumF",
	"Sx/oZ5qv03BvOWk7mcGE+1ZIorZUkuJJJ9nczPk059tS9bUosNvORTLQbnLVMuDrKtmjKfC7xD+qObO9",
	"bLFbbZmomZAMVK/+/TlE4FmT/PQlMtYAjKqUT1cotnvP/QSzNWDIXxbNmkAzsUO21QbVxolO+kA/03zt",
	"G0goACHGzlLfw/NzM4kaCgC/GSV7LM0odC+OYwQ6xrBH0yptWzVTRXSv1/y9DFI9vXJG+t8jtxgjGO3h",
	"scpDfWFkDvGNiGXv6t10w6n/578b7jJ7HxueqdeMfH85ch2NfVCJJYUmUNP1bVIi8g+ObWaEjXYy55PP",
	"fmhW/kh+1/8FAAD//9AU7HsrGwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
